<?php
namespace Raw\Component\Admin\Layout\Definition\Builder;

use Raw\Component\Admin\Layout\Definition\TabNode;

class TabNodeDefinition extends ArrayNodeDefinition
{
    public function __construct($name)
    {
        parent::__construct($name);
        $this->title($name);
    }

    protected function instantiateLayout()
    {
        return new TabNode($this->name, $this->parent);
    }

    /**
     * @return TabsNodeDefinition
     */
    public function end()
    {
        return parent::end(); // TODO: Change the autogenerated stub
    }

    public function title($title)
    {
        return $this->attribute('title', $title);
    }
}