services:

    _defaults:
        autoconfigure:
            true:

    _instanceof:
        Raw\Component\Statistics\StatisticLoaderInterface:
            public: false
            tags:
                - { name: dataset.loader }

    sales.dataset_loader.order:
        class: SalesBundle\Statistics\OrderDatasetLoader
        arguments:
            - '@doctrine.orm.default_entity_manager'