services:

    _defaults:
        autoconfigure:
            true:

    _instanceof:
        Raw\Component\Statistics\StatisticLoaderInterface:
            public: false
            tags:
                - { name: statistics.loader }

    sales.statistic_loader.order:
        class: SalesBundle\Statistics\OrderStatisticLoader
        arguments:
            - '@doctrine.orm.default_entity_manager'